### ISSUE TITLE
Remove magic numbers

### ISSUE THREAD

**Issue by ChumakMike** [artyoda05/MIPZ_practice1#1]
https://github.com/artyoda05/MIPZ_practice1/blob/34be462d50b5ed036c9bcfb529f043153a5d39af/EuroDiffusion/Entities/Country.cs#L12
https://github.com/artyoda05/MIPZ_practice1/blob/34be462d50b5ed036c9bcfb529f043153a5d39af/EuroDiffusion/Entities/Country.cs#L17
https://github.com/artyoda05/MIPZ_practice1/blob/34be462d50b5ed036c9bcfb529f043153a5d39af/EuroDiffusion/Entities/Country.cs#L22
https://github.com/artyoda05/MIPZ_practice1/blob/34be462d50b5ed036c9bcfb529f043153a5d39af/EuroDiffusion/Entities/Country.cs#L27

https://github.com/artyoda05/MIPZ_practice1/blob/34be462d50b5ed036c9bcfb529f043153a5d39af/EuroDiffusion/Entities/City.cs#L17

**Comment by artyoda05** [comment]
Fixed in #https://github.com/artyoda05/MIPZ_practice1/commit/b58e4731d2d87983aef4789fca8276f0bed8a9b9 commit
