### ISSUE TITLE
Exception argument

### ISSUE THREAD

**Issue by IanaKhitsko** [artyoda05/MIPZ_practice1#5]
https://github.com/artyoda05/MIPZ_practice1/blob/b58e4731d2d87983aef4789fca8276f0bed8a9b9/EuroDiffusion/Entities/Country.cs#L14

you dont really you the argument for the exception, why do you need it ?

**Comment by artyoda05** [comment]
Exceptions output and logs are more informative this way. 

![image](https://user-images.githubusercontent.com/15073565/173310787-1c7bf540-75e1-4c29-909c-d3eec2cf1f80.png)
